# Generated by Django 6.0.6 on 2026-06-16 02:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('location_name', models.CharField(max_length=200, verbose_name='Место')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Широта')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Долгота')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость (руб.)')),
                ('rating_transport', models.IntegerField(default=3, verbose_name='Удобство передвижения')),
                ('rating_safety', models.IntegerField(default=3, verbose_name='Безопасность')),
                ('rating_population', models.IntegerField(default=3, verbose_name='Населённость')),
                ('rating_nature', models.IntegerField(default=3, verbose_name='Растительность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Путешествие',
                'verbose_name_plural': 'Путешествия',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TripPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='trips/%Y/%m/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Подпись')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='diary.trip', verbose_name='Путешествие')),
            ],
            options={
                'verbose_name': 'Фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
